version: '3.9'

services:
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=80
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - redis
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development

  worker:
    build: .
    command: celery -A celery_worker.celery_app worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  redis:
    image: redis:7
    ports:
      - "6379:6379"
